### ISSUE TITLE
Inconsistency in displaying blogs in dashboard

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#721]
### **Describe the bug**
Private blogs is also empty but doesn't show text `No Blogs Found...`

https://user-images.githubusercontent.com/54665036/115450002-04a9bb00-a239-11eb-9ebe-57aa935e9d0f.mp4

<hr/>

**Note:**
* Do mention if your are working under GSSoC'21.
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level - 0: 2 days
level - 1: 3 days
level - 2: 4 days
level - 3: 5 days
```

**Comment by Pranav016** [comment]
@Ayush0730 complete previous issues before getting new ones assigned

**Comment by sardonicankita** [comment]
Hi can u assign this issue to me? I am GSSOC'21 participant.

**Comment by Mukta-Sawant** [comment]
Hey, @Pranav016 I think this issue has been resolved already.
![Screenshot (183)](https://user-images.githubusercontent.com/77935961/115588788-bce46b80-a2ec-11eb-9980-89b1aa5b0720.png)

**Comment by Pranav016** [comment]
> Hey, @Pranav016 I think this issue has been resolved already.
> ![Screenshot (183)](https://user-images.githubusercontent.com/77935961/115588788-bce46b80-a2ec-11eb-9980-89b1aa5b0720.png)

I just checked again but this bug is still there..
Maybe we can confirm it from a third person.

**Comment by AnanyaNegi** [comment]
> 
> 
> > Hey, @Pranav016 I think this issue has been resolved already.
> > ![Screenshot (183)](https://user-images.githubusercontent.com/77935961/115588788-bce46b80-a2ec-11eb-9980-89b1aa5b0720.png)
> 
> I just checked again but this bug is still there..
> Maybe we can confirm it from a third person.

It is showing No blogs found text in the private blogs section too. I think someone resolved this bug. I'll be closing this issue.
